import GoogleLayer, {
  GOOGLE_LAYER_TYPES as LAYER_TYPES,
  ADDITIONAL_GOOGLE_LAYERS as ADDITIONA_LAYERS,
} from './GoogleLayer'

export const GOOGLE_LAYER_TYPES = LAYER_TYPES
export const ADDITIONAL_GOOGLE_LAYERS = ADDITIONA_LAYERS

export default GoogleLayer
